services:
  container1:
    image: wrh1997/a1_c1:latest
    ports:
      - 6000:6000
    networks:
      default:
        aliases:
          - c1
  container2:
    image: wrh1997/a1_c2:latest
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - c2
    volumes:
      - $PWD/:/app/data